dataset:
  train_dataset_list: ['AMASS']
  test_dataset: 'AMASS' # NOTE(yyc): you can change this to other structured datasets
  data_dir: 'data'
  stride: [1, 3, 5, 7, 9] # NOTE(yyc): for default testing during training, s will be fixed to max(stride)
  max_stride: 10
  downsample_rate: 10


model_params:
  model_name: 'NetBody25'
  backbone:
    name: 'stgcn'
    graph_args:
        labeling_mode: 'spatial'
    params:
      kp_dim: 3
      window_size: 2
      num_point: 25
  head:
    pred_pose_num: 22
    feat_dim: 335
    input_dim: 256
    hidden_dim: 256
    output_dim: 6
  human_model:
    smpl_dir: 'data/SMPL-family'

  loss_config:
    kp3d: 5.0
    pose: 1.0
    verts: 1.0

train_params:
  batch_size: 128
  num_epochs: 100
  optimizer:
    name: 'AdamW'
    lr: 0.0001
    weight_decay: 0.1
  scheduler:
    name: 'CosineAnnealLR'
  ckpt_save_freq: 20